---
# Source: gitops-project/templates/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: foo-apps
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - env: dev
                - env: nonprod
                - env: prod
          - list:
              elements:
                - name: leave-service
                  repoURL: https://dev.azure.com/acme/Biz-Portal_git/foo-leave-service-k8s-manifests
                - name: intake-service
                  repoURL: https://dev.azure.com/acme/Biz-Portal_git/foo-intake-service-k8s-manifests
  template:
    metadata:
      name: '{{name}}-{{env}}'
    spec:
      project: foo
      source:
        repoURL: '{{repoURL}}'
        targetRevision: HEAD
        path: overlays/{{env}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{$.Values.projectShortName}}-gitops-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
